baseURL = "https://chinae.com.cn/"
theme = "onetwothree"

DefaultContentLanguage = "zh"

[languages]
[languages.zh]
title = "罗坦"
weight = 1

[languages.en]
title = "rrotan"
weight = 2

[languages.jp]
title = "ロタン"
weight = 3

