---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/baby.md
- content/post/happiness.md
- content/post/your-freedom.md
- content/post/empty-is-innocent.md
- content/post/heart.md
- content/post/Dad-says-3.md
- content/post/destined.md
- content/post/love-hate-me.md
- content/post/unique-real-estate.md
- content/post/who-dares.md
- content/post/unreachable-love.md
- content/post/balance.md
- content/post/skill-and-difficulty.md
- content/post/making-limit.md
- content/post/fate.md
- content/post/love-and-believe.md
- content/post/remedy-effect.md
- content/post/nothing-else.md
- content/post/two-way-loss.md
- content/post/level-of-self-control.md
- content/post/peach.md
- content/post/substance-is-empty.md
- content/post/me.md
- content/post/null-and-false.md
- content/post/business-of-no-business.md
- content/post/loss-of-love.md
- content/post/time-principle.md
- content/post/fundamental-difference.md
- content/post/principle-of-constant-light-speed-2.md
- content/post/do-not-mean.md
- content/post/paradox-of-selfish.md
- content/post/relax-or-not.en.md
- content/post/the-desire-of-no-desire.md
- content/post/live-to-die.md
- content/post/ship-of-reincarnation.md
- content/post/where-am-i.md
- content/post/we-meet-here.md
