---
pages:
- post/how-to-obtain-the-necessary-respect.md
- post/ship-of-reincarnation.md
- post/two-fools.md
- post/live-to-die.md
- post/where-am-i.md
- post/we-meet-here.md
- post/relax-or-not.en.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
