---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/principle-of-constant-light-speed-2.md
- content/post/wind-wont-wait-for-you.md
- content/post/level-of-self-control.md
- content/post/unintentional-charity.md
- content/post/do-not-mean.md
- content/post/eternal-double-loss.md
- content/post/empty-is-innocent.md
- content/post/paradox-of-selfish.md
- content/post/relax-or-not.en.md
- content/post/the-desire-of-no-desire.md
- content/post/how-to-obtain-the-necessary-respect.md
- content/post/live-to-die.md
- content/post/ship-of-reincarnation.md
- content/post/where-am-i.md
- content/post/we-meet-here.md
