---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
pages:
- content/post/relax-or-not.en.md
- content/post/loss-of-love.md
- content/post/nothing-else.md
- content/post/how-to-obtain-the-necessary-respect.md
- content/post/the-desire-of-no-desire.md
- content/post/remedy-effect.md
- content/post/love-and-believe.md
- content/post/fate.md
- content/post/making-limit.md
- content/post/paradox-of-selfish.md
- content/post/empty-is-innocent.md
- content/post/do-not-mean.md
- content/post/wind-wont-wait-for-you.md
- content/post/principle-of-constant-light-speed-2.md
- content/post/fundamental-difference.md
- content/post/we-meet-here.md
- content/post/time-principle.md
- content/post/the-man-unafraid-of-death.md
- content/post/where-am-i.md
- content/post/ship-of-reincarnation.md
- content/post/live-to-die.md
- content/post/hedge-fund-and-sex-chromosome.md
- content/post/heart.md
- content/post/me.md
- content/post/null-and-false.md
- content/post/unintentional-charity.md
- content/post/substance-is-empty.md
- content/post/peach.md
- content/post/level-of-self-control.md
- content/post/two-way-loss.md
- content/post/business-of-no-business.md
- content/post/hedgehog-rider.md
